export const CALCULATION_REPOSITORY_TOKEN = Symbol(
  'CALCULATION_REPOSITORY_TOKEN',
);
export const CALCULATION_REPOSITORY_PERSIST_TOKEN = Symbol(
  'CALCULATION_REPOSITORY_PERSIST_TOKEN',
);

export const QUERY_DECRYPTER_INTERFACE = Symbol('QUERY_DECRYPTED_INTERFACE');
